# Generated by Django 5.2.6 on 2026-09-16 10:31
from django.contrib.postgres.operations import TrigramExtension

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_tags'),
    ]

    operations = [
        TrigramExtension()
    ]
